#! /bin/sh

set -e

ln -sf /usr/share/futuresonic/futuresonic.sh /usr/bin/futuresonic

chmod 750 /var/futuresonic

# Clear jetty cache.
rm -rf /var/futuresonic/jetty

# Configure FutureSonic service.
update-rc.d futuresonic defaults 99

# Start FutureSonic service.
invoke-rc.d futuresonic start
